### ISSUE TITLE
PowerDNS version support

### ISSUE THREAD

**Issue by asrud** [ArnesSI/netbox-powerdns-sync#1]
Which latest PowerDNS version is supported?
It seems there are some changes in API (PowerDNS Authoritative Server 4.5.3).

An exception occurred: PDNSError: code=404 http://xxxxxxx:8053/servers: Not found

Indeed,
curl localhost:8053/servers: Not Found
The url seems to be
curl localhost:8053/api/v1/servers: Unauthorized

I'm ready to downgrade PowerDNS in order to use your plugin :)

**Comment by matejv** [comment]
Does it work if you put http://xxxxxxx:8053/api/v1 into API URL field?

**Comment by asrud** [comment]
Wow, it's so easy to fix! 
By bad :)

```
Line | Level | Message
-- | -- | --
1 | Default | Starting sync for zone spec.antn.in.
2 | Info | Found 2 matching addresses to check
3 | Info | Found record count: netbox:2 pdns:0
4 | Info | Record change count: to_delete:0 to_create:2
5 | Success | Finished

```

And IP addresses created it Netbox appear in PowerDNS after sync indeed.
Awesome!  Thx!

**Comment by matejv** [comment]
Glad to hear it's working for you! :D
